name: pcanvas_flutter
description: Flutter implementation of `PCanvas` for the package `pcanvas`.
version: 1.0.1
homepage: https://github.com/gmpassos/pcanvas_flutter

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pcanvas: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#dependency_overrides:
#  pcanvas:
#    path: ../pcanvas
